export const SEO_CHECKLIST = [
  "✅ Unique <title> on every page",
  "✅ Meta description 140-160 chars on every page",
  "✅ One H1 per page containing primary keyword",
  "✅ H2s contain secondary keywords",
  "✅ All images have keyword-rich alt text",
  "✅ All images in WebP format",
  "✅ JSON-LD structured data on all pages",
  "✅ FAQPage schema on homepage",
  "✅ Product schema with pricing",
  "✅ XML sitemap at /sitemap.xml",
  "✅ robots.txt at /robots.txt",
  "✅ Canonical URLs on all pages",
  "✅ Open Graph tags complete",
  "✅ Twitter Card tags complete",
  "✅ Internal links use descriptive anchor text",
  "✅ Core Web Vitals — LCP under 2.5s",
  "✅ Core Web Vitals — CLS under 0.1",
  "✅ Core Web Vitals — INP under 200ms",
  "✅ Mobile responsive at 375px",
  "✅ HTTPS enforced",
  "✅ No broken internal links",
  "✅ Blog posts target long-tail keywords",
  "✅ UK English spelling throughout",
  "✅ hreflang en-gb declared",
  "✅ Page speed score 90+ on Lighthouse",
];
